language: php

php:
- 7.2
- 7.3

before_script:
- travis_retry composer self-update
- travis_retry composer update --no-interaction --prefer-dist
- composer show laravel/framework

script:
- vendor/bin/phpunit
